### PR TITLE
Packages in multiple paths

### PR DESCRIPTION
**Pull request by hroncok**
This is a work in progress, just that it is clear what I'm doing.

This aims to implement #316 and also fix related stuff found on the way.

Do **not merge** until I say it's finished :)

### CODE REVIEW

**Comment by hroncok** [comment]
So, I guess that's it. Still don't merge this, there are still some things that had to be done (our favorites):

 * [ ] tests
 * [ ] docs

However, I'm not writing those unless someone (@bkabrda I guess) confirms that what I have done is what was expected.

This also needs real live testing (i.e. running the commands).

**Comment by bkabrda** [comment]
You could write a bit more comments, reading four nested loops without comments gives me headaches ;) All the path setup in settings would also deserve some comments, it's starting to be pretty complicated.
I'd also advise using empty lines to separate logically coherent sections of code, it really helps.

Otherwise this LGTM, so once you write tests, docs and some additional code comments, we can merge this.

**Comment by hroncok** [comment]
This has rotted here long enough so Github now cannot even merge it via the UI. I suggest I merge this in the command line, resolve conflicts and add the tests and docs in separate PR - so we don't diverge with master so much that merging would be pain.

**Comment by bkabrda** [comment]
+1, feel free to merge this.

**Pull request merged**
