### PR TITLE
dapicli.py: os.geteuid is absent on Windows

### PR DESCRIPTION
**Pull request by techtonik**
This allows to get command line help on this platform

### CODE REVIEW

**Comment by hroncok** [comment]
Thanks. This part of code is currently being relocated somewhere else in #334. So I will think about it there.

However, why do we need to support this on Windows, when those directories are unix-style anyway?

**Comment by bkabrda** [comment]
This is actually interesting. Are you trying to run DevAssistant on windows, @techtonik ? If so, I'm assuming it doesn't really work, but I'm interested in how many issues there are or if you have plans to send us more PRs to make it work. Thanks!

**Comment by techtonik** [comment]
I tried to run it on Windows, right. It installed successfully, which was a surprise, but then failed and I thought that if it is written in Python, I could get it running there pretty quickly. However, when I saw that it looks like I need to wrap a project I wanted to checkout into yet another package format, I stopped.

I expected command line interface to be more intuitive, e.g. without going to website to read the theory. I just wanted to run da over GitHub URL to see if it can fetch and detect some setting that were set there. Maybe proposing to add container, run CI etc.

**Comment by bkabrda** [comment]
Thanks for the info.

Well, you don't need to wrap the *project* into another format, you just need to wrap DevAssistant plugins into this format. AFAICS there is no general cross-platform way to distribute plugins - I mean such that it doesn't require knowledge of a certain programming language (like, we could theoretically bend Python packages to carry assistants, but that would be *really* ugly and I doubt most of non-Python developers would want to touch that).

The intuitivness of command line interface is a thing that we're strugling with a bit... I'm kind of hoping that beginners will use the GUI and then perhaps in time move to CLI (well, current GUI has to be remade without a question, but people *do* use it and they seem to be quite ok with it). That said, I have no idea if/how pygobject works on windows. All of us are Linux folks, so there hasn't yet been any effort to make DA work on windows.

If you have some specific suggestions for improving the CLI interface, I'd love to hear them. Thank you for your comments, I really appreciate honest feedback!

**Comment by techtonik** [comment]
That's nice. =) Well, to make interface better, the best way is to work with user **expectations** and anticipate them. What do I (as the lazy Dev) expect from assistant is that it will be intuitive enough to just do the magic. This requires **guessing the context**. I expect it to work without asking me too much, meaning that if something goes wrong I hit <kbd>Esc</kbd> or <kbd>Ctrl-C</kbd> and only then it will stop/pause ask something like `Huh?`

Example, I enter `da http://github.com/...` and it starts to checkout the source. Then detect some tooling, download it, setup. It is ok for it to do mistakes - people do it as well, so it should be just easy to revert and correct it.

For the given time, when there are no `modules` for da on my system, it will be nice to have some short intro about that when I attempt to run command. I still don't know what `assistant` is exactly, so it might be like:

    > da tweak http://github.com/...
    Looks like you don't have any modules installed that can process your
    command. da modules are called assistants. Most likely you need 'GitHub'
    assistant. Fetch and install it (Y/n)? 

I expect da to be fully interactive command, so there should be no problem in preserving backward compatibility etc. Users should be able to learn da (and teach it) from scratch,

**Pull request closed without merging**
