### PR TITLE
Use function to detect root user

### PR DESCRIPTION
**Pull request by techtonik**

### CODE REVIEW

**Comment by hroncok** [comment]
Thanks. What platforms is this targeting?

**Comment by tradej** [comment]
Thank you for the pull request. I join Miro's question about what platform this is targeting—it appears to me that it's Windows, which, mind you, we don't support. However, if it doesn't break the code, I'll be glad to greenlight any PR regarding Windows. One note about that—We're rewriting DA to use the client/server architecture, and intend to run the server inside a Linux-based container on Windows, so you may not need to run DA directly on bare-metal Windows at all when that's done.

Now, speaking of the PR, I am not a fan of having utility functions in `devassistant.settings`. I'd like to ask you to use something like this instead, and re-submit the PR:
```
try:
    if os.geteuid() == 0:
        DATA_DIRECTORIES = DATA_DIRECTORIES[1:]
except AttributeError: # Not UNIX
    pass

**Comment by techtonik** [comment]
Yes, it is about Windows, but also may happen on any single user platform with Python. I used NotUNIX as a keyword to be universally reused in such places that may need further tweaking.

**Comment by techtonik** [comment]
Ready to review in PR #392.

**Pull request closed without merging**
