### PR TITLE
Replace HighContrast icons with symbolic icon

### PR DESCRIPTION
**Pull request by mcatanzaro**
Hi, Jakub Steiner made a symbolic icon for devassistant. We're aiming for every application installed by default in Fedora 22 to have a symbolic icon.

If you could take care of the changes to the Fedora package, that would be much appreciated.

### CODE REVIEW

**Comment by tradej** [comment]
Hi, thanks for the icon. Please add licensing information to `README.md` at the bottom, thank you. Suggestion:
```
Symbolic icon taken from GNOME Project (http://gnome.org) under the CC-BY-SA license.
```

**Comment by hroncok** [comment]
I don't think this icon was taken from GNOME project, it was created for DevAssistant. And as far now we have no separate content license for icons, I guess we can keep it this was. I would than suggest to add Jakub Steiner to CONTRIBUTORS.

**Comment by mcatanzaro** [comment]
I dunno if he'd want to appear in CONTRIBUTORS just for creating the icon. Actually, I dunno how much he did: normally he just runs the old high contrast icon through a script to create the symbolic icon, but it's possible he did more for this one since your high contrast icon was in a different style from the others.

Regarding license: you can choose the license you prefer, in which case he recommends CC-BY-SA, but it's easiest to just use the license of the project (at least in GNOME we don't distribute icons under separate licenses).

**Comment by tradej** [comment]
I assumed it was [this icon](https://github.com/gnome-design-team/gnome-icons/blob/master/apps-symbolic/Adwaita/scalable/apps/devassistant-symbolic.svg), hence the request for proper licensing information. If it's the intention to keep the license of DevAssistant, this is good to go.

**Comment by mcatanzaro** [comment]
Yes, feel free to use the license of devassistant: that's what we've done for most of the other icons in that repo. I can have him confirm here if you're paranoid.

Also a request regarding the Fedora package: if there's not going to be a new devassistant release before the feature freeze, please backport this icon so that it can make the F22 release. Thanks. :)

**Comment by hroncok** [comment]
So this file:

**Comment by hroncok** [comment]
So this file:

    distribution/icons/hicolor/symbolic/devassistant-symbolic.svg

Should be installed as

    %{_datadir}/icons/hicolor/scalable/apps/devassistant-symbolic.svg

(as explained [here](https://wiki.gnome.org/Initiatives/GnomeGoals/HighContrastAppIcons))

Not:

    %{_datadir}/icons/hicolor/symbolic/devassistant-symbolic.svg

(as the location in the source tree suggests)

Am I getting this right?

**Comment by hroncok** [comment]
Using `%{_datadir}/icons/hicolor/symbolic/apps/devassistant-symbolic.svg` as learned on IRC.

**Pull request merged**
